In [6]:
print('hello Jup!')

hello Jup!


In [2]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [8]:
odd_number_list = [1,3,5]


In [11]:
np.array(odd_number_list)

array([1, 3, 5])

In [12]:
two_dim = [[11,11,11], [22, 22, 22],[33, 33,33]]
np.array(two_dim)

array([[11, 11, 11],
       [22, 22, 22],
       [33, 33, 33]])

In [15]:
np.arange(0, 9, 2)

array([0, 2, 4, 6, 8])

In [16]:

np.zeros(9) #только нули

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3 ,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,3))#только единицы

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0,5 ,5)#равномернораспредлпеные числа

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [22]:
#identity квадратная матрица с 0 и 1(по главной диагонали)
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(3)

array([0.4035338 , 0.44970299, 0.8098466 ])

In [24]:
np.random.rand(3, 4)

array([[0.58598657, 0.5199602 , 0.87906319, 0.23995637],
       [0.42852393, 0.82547003, 0.79395838, 0.69203102],
       [0.12965582, 0.12488838, 0.1798861 , 0.08659358]])

In [27]:
np.random.randint(0, 50,20)



array([ 6, 23, 13, 28,  4, 28,  2, 32, 21, 28,  7, 46,  9,  3,  1, 42, 31,
       43, 36, 18])

In [31]:
rand_arr = np.random.randint(0, 50,20)
rand_arr.reshape(4,5)


#%i9%max максимальное значение массиыва
rand_arr.max()
rand_arr.min()
rand_arr.argmax()
rand_arr.argmin()

array([[24, 16, 31, 48, 46],
       [ 1, 35, 16, 33, 30],
       [ 2,  0, 25, 22, 13],
       [13, 10, 16, 43,  8]])

In [33]:
mass = np.ones(20)

mass.reshape(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
int_arr = np.random.randint(0, 10, 10)
print(int_arr)

[5 7 0 1 0 1 0 9 4 9]


In [8]:
int_arr[0]

5

In [9]:
int_arr[1:4]

array([7, 0, 1])

In [12]:
arr=np.arange(0,10)
new_arr = arr[:4]
print(new_arr)
new_arr[2:] = 7

[0 1 2 3]


In [14]:
new_arr=arr.copy()
#если все числа хотим заменить например на 0
new_arr[:] = 0
print(new_arr)


[0 0 0 0 0 0 0 0 0 0]


In [15]:
print(arr>3)

[False False False False  True  True  True  True  True  True]
