In [2]:
print('hello Jup!')

hello Jup!


In [3]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [4]:
odd_number_list = [1,3,5]


In [5]:
np.array(odd_number_list)

array([1, 3, 5])

In [6]:
two_dim = [[11,11,11], [22, 22, 22],[33, 33,33]]
np.array(two_dim)

array([[11, 11, 11],
       [22, 22, 22],
       [33, 33, 33]])

In [7]:
np.arange(0, 9, 2)

array([0, 2, 4, 6, 8])

In [8]:

np.zeros(9) #только нули

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3 ,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3))#только единицы

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0,5 ,5)#равномернораспредлпеные числа

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [12]:
#identity квадратная матрица с 0 и 1(по главной диагонали)
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(3)

array([0.46124831, 0.7446309 , 0.3720011 ])

In [14]:
np.random.rand(3, 4)

array([[0.44788928, 0.48554882, 0.63553192, 0.29455684],
       [0.26044812, 0.44508323, 0.09239787, 0.27404602],
       [0.670627  , 0.52505753, 0.20474073, 0.75634539]])

In [15]:
np.random.randint(0, 50,20)



array([ 6, 30, 18, 24, 12, 15,  4, 22, 37, 41, 13,  4, 48, 10, 21, 14, 15,
        9, 49, 26])

In [16]:
rand_arr = np.random.randint(0, 50,20)
rand_arr.reshape(4,5)


#%i9%max максимальное значение массиыва
rand_arr.max()
rand_arr.min()
rand_arr.argmax()
rand_arr.argmin()

4

In [17]:
mass = np.ones(20)

mass.reshape(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
int_arr = np.random.randint(0, 10, 10)
print(int_arr)

[4 1 8 9 5 3 4 6 2 7]


In [19]:
int_arr[0]

4

In [20]:
int_arr[1:4]

array([1, 8, 9])

In [21]:
arr=np.arange(0,10)
new_arr = arr[:4]
print(new_arr)
new_arr[2:] = 7

[0 1 2 3]


In [22]:
new_arr=arr.copy()
#если все числа хотим заменить например на 0
new_arr[:] = 0
print(new_arr)


[0 0 0 0 0 0 0 0 0 0]


In [23]:
print(arr>3)

[False False  True  True  True  True  True  True  True  True]


In [24]:
two_dim=np.arange(12).reshape(3,4)
print(two_dim)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
#результат один итот же

two_dim[1][1]
two_dim[1,1]

5

In [26]:
print(two_dim[:2,:2])
print(two_dim[:2,2:4])



[[0 1]
 [4 5]]
[[2 3]
 [6 7]]


In [27]:
int_array=np.random.randint(0,20,10)
mas=int_array[1:6]
print(int_array)
print(mas)


[18  8  8  9  8  9 19 15  2  0]
[8 8 9 8 9]


In [28]:
import numpy as np
arr = np.random.randint(3, 12, 12).reshape(4, 3)
new_arr = arr[1:3, :2]
print(arr)
print(new_arr)

[[ 9  5 10]
 [ 4  5  3]
 [ 6 10  9]
 [ 8 11 10]]
[[ 4  5]
 [ 6 10]]


In [29]:
"""Создайте двумерный массив ,
состоящий из случайных целых чисел из
диапазона от 0 до 9, в котором 4 строки и 6 столбцов.
 Затем создайте массив состоящий из элементов ,
 которые больше числа 3. Выведите значения обоих
 массивов при помощи функции print()"""
import numpy as np
arr = np.random.randint(0, 9, 24).reshape(4, 6)
new_arr = arr[arr>3]
print(arr)
print(new_arr)

[[7 1 3 0 6 0]
 [3 5 8 3 3 8]
 [7 0 0 8 6 7]
 [1 4 6 6 8 7]]
[7 6 5 8 8 7 8 6 7 4 6 6 8 7]


In [30]:
arr=np.arange(1,11)
print(arr)
print(arr + arr)
print(arr*arr)
print(arr/3)
print(arr*3)
print(arr**2)
print(np.sqrt(arr))
np.max(arr)
arr.max()

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[  1   4   9  16  25  36  49  64  81 100]
[0.33333333 0.66666667 1.         1.33333333 1.66666667 2.
 2.33333333 2.66666667 3.         3.33333333]
[ 3  6  9 12 15 18 21 24 27 30]
[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


10